output: "cuffdiff_out"
threads: "12"
merged_gtf:
    class: File
    path: ./merged/merged.gtf
condition1_files:
   - {class: File, path: ./normal1/abundances.cxb}
condition2_files:
   - {class: File, path: ./tumour1/abundances.cxb}
