input_script: 
   class: File
   path: ../../scripts/salmon_R_script.R
gtf: 
   class: File
   path: /path/to/file
metadata:
   class: File
   path: /path/to/file
quant_results:
   class: Directory
   path: /path/to/Directory
