input_bam:
  class: File
  path: /project/home18/apg3718/SRR3584106Aligned.out.sorted.bam
threads: 4
annotation:
  class: File
  path: /project/home18/apg3718/SRR3584106.gtf
outfilename: stringtie.out.gtf
